### ISSUE TITLE
Events subscription api

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#240]
Provide a subscription `api` for events:

- [ ] Trigger event on error
- [ ]  Trigger event when page load / change.
- [ ] More ? ...

**Comment by DaniAcu** [comment]
QQ: When you trigger an error you expect that the component shows some alert or something. Because if we have some error I suppose that the component could be work wrong. So maybe it's a good idea to put a message to say to the user that report that fails if he wants as an issue on the repo. But it's only an idea. In any case, what's the status that you expect when the component when that fails and an error happened?

**Comment by btzr-io** [comment]
Actually there is a component for that:
https://github.com/btzr-io/Villain/blob/master/packages/villain-react/src/components/renderError.js

I like the idea of adding a link or button to report the issue :+1:

**Comment by btzr-io** [comment]
This api will be used when developers need to do something when a certain event occurs, like showing a custom error view.

**Comment by btzr-io** [comment]
I'll merge this issue with: #446
