### ISSUE TITLE
Smart tooltip position

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#94]
- [ ] Fix inconsistency on tooltip position.
- [x] Make `tooltip` position to be always visible ( left, right , top, bottom, center )

See current behavior:

![Screenshot_2019-10-20 Screenshot](https://user-images.githubusercontent.com/14793624/67167706-4a42aa80-f35a-11e9-9740-e5a355b202b2.png)

![Screenshot_2019-10-20 Screenshot(1)](https://user-images.githubusercontent.com/14793624/67167768-ac031480-f35a-11e9-801d-dbd53ade5d4a.png)

@jonathanmcchesney Any ideas why this is not working on the `navigation` component ?

**Comment by jonathanmcchesney** [comment]
The tooltip seems to be right aligning with a slight right margin to the toolbar component it is called on. Because of this as the text my sometimes be larger than the distance to the edges of the parents container it is overflowing. Could add a text wrap style or something similar (maybe try out the overflow styling) to mitigate this.

**Comment by btzr-io** [comment]
@jonathanmcchesney I think some `js` will be required to handle this properly

**Comment by jonathanmcchesney** [comment]
Agreed. I think both the tooltips should also be using the same styles or js if possible, their functionally at least at the moment is identical.
